name: Publish package to NPM and GitHub registry

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - registry: https://registry.npmjs.org/
            token_secret_key: NPM_TOKEN
          - registry: https://npm.pkg.github.com/
            token_secret_key: GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936

      - name: Setup Node.js
        uses: actions/setup-node@d1b197b965eb46e1a1878caad41c4ab3efae133f
        with:
          node-version-file: .node-version
          cache: "npm"
          check-latest: true
          registry-url: ${{ matrix.registry }}

      - name: Install dependencies
        run: npm ci

      - name: Build and Compile TypeScript project
        run: npm run build

      - name: Generate package files
        run: node publish.js

      - name: Publish package to npm and GitHub packages registry
        run: cd package && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.token_secret_key] }}
