name: Publish package to NPM and GitHub registry

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - registry: https://registry.npmjs.org/
            token_secret_key: NPM_TOKEN
          - registry: https://npm.pkg.github.com/
            token_secret_key: GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891

      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: .node-version
          cache: "npm"
          check-latest: true
          registry-url: ${{ matrix.registry }}

      - name: Install dependencies
        run: npm ci

      - name: Build and Compile TypeScript project
        run: npm run build

      - name: Generate package files
        run: node publish.js

      - name: Publish package to npm and GitHub packages registry
        run: cd package && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.token_secret_key] }}
